on:
  push:
  pull_request:

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use npm cache
        uses: actions/setup-node@v3
        with:
          cache: "npm"
      - run: npm ci
      - name: Run check-format
        run: npm run check-format
